// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV2Tc0HqEhkF0WS3kAy9pFRAN6FEaxYHY',
    appId: '1:252771998682:web:01b6aed89e4ee4b20cfee3',
    messagingSenderId: '252771998682',
    projectId: 'thirtyconcepts-8808c',
    authDomain: 'thirtyconcepts-8808c.firebaseapp.com',
    storageBucket: 'thirtyconcepts-8808c.appspot.com',
    measurementId: 'G-Q4XC2HYZEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWF0TxUbueYxB_OwrsfAltbYQ9QrVwUb0',
    appId: '1:252771998682:android:6d1c0b6b8c70e7a10cfee3',
    messagingSenderId: '252771998682',
    projectId: 'thirtyconcepts-8808c',
    storageBucket: 'thirtyconcepts-8808c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3o03tjfS_-DmNYAknZo8Zkw8lefrDn3I',
    appId: '1:252771998682:ios:64071a33981fd8780cfee3',
    messagingSenderId: '252771998682',
    projectId: 'thirtyconcepts-8808c',
    storageBucket: 'thirtyconcepts-8808c.appspot.com',
    iosBundleId: 'com.example.thirtyDaysThirtyWidgets',
  );
}
